### ISSUE TITLE
Staff of the Woodlands

### ISSUE THREAD

**Issue by panosl** [Cphrampus/DnDAppFiles#370]
It there a way to register it as a quarterstaff?

Right now I've added two items, the staff and a quarterstaff +2 to make it usable.

**Comment by panosl** [comment]
Maybe we should just change the type from ST, to M, but that doesn't sound right.

**Comment by Cphrampus** [comment]
I agree, it is annoying that it does not present a way to be used as a melee weapon, however I'm not sure about the change either.

Mainly, this would move probably all of the staff magic items out of the "Wondrous Items" section in the compendium and into the "Weapons" section, specifically magic weapons. While this isn't technically incorrect (it _is_ a magic melee weapon), it seems odd that it would need to disregard the ability to mark something as a Staff, since it is a specific item type in the app.

The compendium itself is searchable in both apps, but the iOS version specifically separates out Staffs as a section when adding items to a character, whereas the Android version has the user select either Wondrous Items or Weapons.

It is possible to simply edit the item to be a quarterstaff after adding it, but that's not really a good solution either.
