### ISSUE TITLE
Cannot import Classes

### ISSUE THREAD

**Issue by InflamedSebi** [Cphrampus/DnDAppFiles#393]
Hey, I tried to use the files with https://store.steampowered.com/app/1087080/Critical_Compendium/ since they claim to be compatible to DM5, but i can't seem to import Classes correctly. Especially those who are Subclasses like the Celestial Warlock. they just won't show up.
Also importing the UA artificer is telling me a Hit dice of "d0" which is clearly not right.
I also tried using GM5 but seems like it does not even support classes in the compendium.
Am I just using the wrong tools or are the files not meant to be used like that?

thanks in advance :)

**Comment by Cphrampus** [comment]
Hey,

There are multiple points here, so I'm just going to tackle them one at a time.

Critical Compendium Compatibility
---

I am not familiar with Critical Compendium and looking at the steam page, I can't see where they are claiming compatibility with the DM5/Lion's club app format. Could you point me to that? I also try to fix this below, but I'd be curious to see this anyway.

Importing Classes
---

I am a bit confused by this problem as well, when you say you can't import the classes "Especially those who are Subclasses like the Celestial Warlock", does this mean you are trying to import the "Warlock (Celestial).xml" file, rather than one of the generated compendiums?

If so, that would be the problem. As stated in the Readme "Not all files use a format consumable by GM5 and Fight Club, in particular the various files under Classes use <subclass> and <spellList> tags that compile into standard format with the create_compendiums.py python script".

In general, the script should always be used to create the files for importing into the app, this allows more freedom in both custom xml tags, as are currently used, and the ability to manipulate the shape of the underlying data, e.g., changing the file structure or type completely, for ease of the script/working on the data.

This is also the reason for the disclaimer in the same file of not using the files if you don't know what you are doing, since they are a work in progress and not guaranteed to work, so there may be fiddling that must be done with the data or script, which may make its way back to the repo, depending on how specific to the user's workflow it is.

Artificer Hit Die
---

This does seem to be a problem from a lack of proofreading/making artificers recently, resolved in #394

GM 5 and classes
---

The GM5 app doesn't support classes, the compendium used there is really a subset of the FC5 one. This is because characters only need relevant data for combat, so things like classes and the leveling aspects of those don't matter as much compared to attack bonuses in a fight, so these are just free text, more for DM reference.

Hopefully those help with your question.

**Comment by InflamedSebi** [comment]
oh just looked that up. they did not claim to be compatible to DM5, but compatible to Fight Club, but as far as i can see, this should be the same format.
https://steamcommunity.com/app/1087080/discussions/1/1638661595064091094/

And yes I tried to import the classes directly without the script. Imma give it a try later with the script.
Ty for your reply :)

**Comment by Cphrampus** [comment]
Just wanted to follow up on this, was not using the script the problem?

**Comment by Cphrampus** [comment]
I'm going to close this for lack of activity
